
--
CREATE TABLE einsteinrepository.PENDING_TASK (
	ID BINARY NOT NULL,
	REQUEST_ID BINARY NOT NULL,
	CREATE_DATE DATETIME NOT NULL,
	RUNNING BIT NOT NULL
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8
COLLATE=utf8_general_ci ;



