
--
CREATE TABLE `PENDING_TASK` (
  `ID` binary(64) NOT NULL,
  `REQUEST_ID` binary(64) NOT NULL,
  `CREATE_DATE` datetime NOT NULL,
  `RUNNING` bit(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

